version: "3.8"
services:
  jwks-cache:
    image: ghcr.io/jaconi-io/jwks-cache:latest
    ports:
      - 8090:8080
    volumes:
      - type: bind
        source: ./jwks-cache.yaml
        target: /workspace/config/application.yaml

  dex:
    image: ghcr.io/dexidp/dex:latest
    ports:
      - 5556:5556
    volumes:
      - type: bind
        source: ./dex.yaml
        target: /etc/dex/config.docker.yaml

  micronaut-test:
    image: micronaut-test:latest
    ports:
      - 8080:8080
