micronaut:
  application:
    name: micronaut-test

  security:
    token:
      jwt:
        signatures:
          jwks:
            dex:
              url: http://jwks-cache:8080/.well-known/jwks.json
